---
resources:
- name: attendee-service-source
  type: git
  source:
    uri: https://github.com/iamranga/pcf-attendee-service-code.git
    branch: master

- name: deploy-attendee-service
  type: cf
  source:
    api: https://api.system.dev.digifabricpcf.com
    username: Rangarajan.Ramadass@cognizant.com
    password: Peace001
    organization: rramadass-pal
    space: sandbox
    skip_cert_check: true

jobs:
- name: test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
  - task: test
    file: attendee-service-source/ci/tasks/test.yml

- name: deploy
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [test]
  - task: package
    file: attendee-service-source/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service-source/manifest.yml
      path: package-output/attendee-service.jar

- name: smoke_test
  public: true
  plan:
  - get: attendee-service-source
    trigger: true
    passed: [deploy]
  - task: smoke_test
    file: attendee-service-source/ci/tasks/smoke-test.yml
    params:
      ATTENDEE_SERVICE_URL: http://attendee-service-phlegmiest-avion.app.dev.digifabricpcf.com
